[package]
name = "libcrypt-songbird"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later WITH Bison-exception-2.2"
description = "Songbird Encryption SB-01"

[lib]
name = "songbird"
path = "src/lib.rs"

[dependencies]
thiserror = "2.0.8"
