[package]
name = "ariadne"
version = "0.1.0"
edition = "2021"

[lib]
name = "songbird"
path = "src/lib.rs"

[dependencies]
thiserror = "1"
pqcrypto = "0.18.1"
hkdf = "0.11"
sha3 = "0.10"
chacha20 = "0.9"
rand = "0.8"